# Site settings
title: My thoughts
url: "https://devltest.github.io"
baseurl: ""
#timezone: Asia/Chongqing
description: >
  This is my blog at which I
  throw my thoughts

# Your information
email: your_email@example.com
author: hello world
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: One sentence introducing yourself.
twitter_username: twitter_username
github_username:  devltest
profile_links:
  Email: "mailto:your_email@example.com"
  GitHub: "https://github.com/devltest"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
